[package]
name = "dylang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.object]
version = "0.29.0"
features = ["read_core", "write_core", "elf", "pe"]
